[package]
name = "catsay"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
assert_cmd = "2.0.17"
clap = { version = "4.2.1", features = ["derive"] }
colored = "2.0.0"
predicates = "3.0.2"
